packages:
  - packages/*
  - playground
  - docs
allowBuilds:
  esbuild: true
minimumReleaseAgeExclude:
  - tsdown@0.22.4

catalogs:
  dev:
    '@tsconfig/node24': ^24.0.4
    '@types/node': ^24.13.2
    '@types/throttle-debounce': ^5.0.2
    '@vitejs/plugin-vue': ^6.0.7
    '@vitejs/plugin-vue-jsx': ^5.1.6
    '@vue/tsconfig': ^0.9.1
    csstype: ^3.2.3
    npm-run-all: ^4.1.5
    npm-run-all2: ^9.0.2
    tsdown: ^0.22.4
    tsx: ^4.23.0
    typescript: ^6.0.3
    vite: ^8.0.16
    vite-plugin-dayjs: ^1.0.2
    vite-plugin-inspect: ^11.4.1
    vite-plugin-tsx-resolve-types: ^1.0.1
    vite-plugin-vue-devtools: ^8.1.2
    vue-tsc: ^3.3.7
  prod:
    '@vueuse/core': ^14.3.0
    dayjs: ^1.11.21
    es-toolkit: ^1.49.0
    scroll-into-view-if-needed: ^3.1.0
    throttle-debounce: ^5.0.2
    vue: ^3.5.39
