name: deploy-site

on:
  workflow_run:
    workflows: [Test]
    types: [completed]

concurrency:
  group: deploy-site-main
  cancel-in-progress: true

jobs:
  # 构建工作
  build:
    # Test 绿 + main 分支才部署
    if: >
      ${{
        github.event.workflow_run.conclusion == 'success' &&
        github.event.workflow_run.head_branch == 'main'
      }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          # 确保部署的是“通过测试的那次提交”
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Build site
        run: |
          pnpm build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/.vitepress/dist

  # 部署工作
  deploy:
    environment:
      name: ${{ github.event.repository.name }}
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
